### ISSUE TITLE
Unknown provider: bProvider <- b <- ngPhotoswipeDirective

### ISSUE THREAD

**Issue by cab00m** [m00s/angular-photoswipe#2] opened 2015-12-11 18:13 UTC
Hi, 

your demo script gets the error:

"Error: $injector:unpr
Unknown Provider
Unknown provider: bProvider <- b <- ngPhotoswipeDirective"

Can you help me to run the demo?

**Comment by m00s** [comment] 2015-12-11 21:02
Hi @cab00m
The error is caused by this [2 lines](https://github.com/m00s/angular-photoswipe/blob/master/angular-photoswipe.js#L30-L31) that for now you can remove.

I'll release a fix in the next days. 
Thanks for the report

**Comment by cab00m** [comment] 2015-12-11 22:29
Ok, thank you for your help!

**Comment by m00s** [comment] 2015-12-18 20:39
@cab00m Minification issue. Fixed with v0.0.7.

I close this, reopen if you need

**Closed as completed by m00s** 2015-12-18 20:39 UTC
